### ISSUE TITLE
serving mpt-7b-bigdl.yaml crash when install with pip install -e .[bigdl-cpu]

### ISSUE THREAD

**Issue by xwu99** [intel/llm-on-ray#58]
First create an new conda env with python 3.9, and install with

`pip install -e .[bigdl-cpu] -f https://developer.intel.com/ipex-whl-stable-cpu -f https://download.pytorch.org/whl/torch_stable.html`

Then run: 

`python inference/serve.py --config_file inference/models/bigdl/mpt-7b-bigdl.yaml --serve_simple`

It looks something is messed after installing bigdl-llm: 

![image](https://github.com/intel/llm-on-ray/assets/23566414/974042d6-1160-48b0-a90c-6d87dc52552b)

After I switched to another env, it's OK.

@KepingYan @jiafuzha

**Comment by xwu99** [comment]
I did some test and found fastapi 0.109 and starlette 0.35.1 cause the crash, 
I reinstall fastapi 0.104 and starlette 0.27.0 it's OK.

**Comment by KepingYan** [comment]
After installing env via `pip install .[cpu] -f https://developer.intel.com/ipex-whl-stable-cpu -f https://download.pytorch.org/whl/torch_stable.html`, I also encountered this problem. `fastapi` is installed together with `ray[serve]`, I've verified 0.104<=fastapi<=0.109 all works well. The above problem will be fixed by https://github.com/intel/llm-on-ray/pull/61.
